{% set version = "3.2-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-betareg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/betareg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/betareg/betareg_{{ version }}.tar.gz
  sha256: 10b49ebfb1dafbe890df41decb4ec82d38deb240c817273f5fcf674f8d07b3e4

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-formula
    - r-flexmix
    - r-lmtest
    - r-modeltools
    - r-sandwich
  run:
    - r-base
    - r-formula
    - r-flexmix
    - r-lmtest
    - r-modeltools
    - r-sandwich

test:
  commands:
    - $R -e "library('betareg')"           # [not win]
    - "\"%R%\" -e \"library('betareg')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=betareg
  license: GPL-2 | GPL-3
  summary: Beta regression for modeling beta-distributed dependent variables, e.g., rates and proportions. In addition to maximum likelihood regression (for both mean and precision of a beta-distributed response), bias-corrected and bias-reduced estimation as well as finite mixture models and recursive partitioning for beta
    regressions are provided.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - sebastian-luna-valero

# Package: betareg
# Version: 3.1-2
# Date: 2018-05-16
# Title: Beta Regression
# Authors@R: c(person(given = "Achim", family = "Zeileis", role = c("aut", "cre"), email = "Achim.Zeileis@R-project.org"), person(given = "Francisco", family = "Cribari-Neto", role = "aut", email = "cribari@ufpe.br"), person(given = "Bettina", family = "Gruen", role = "aut", email = "Bettina.Gruen@jku.at"), person(given = "Ioannis", family = "Kosmidis", role = "aut", email = "ioannis@stats.ucl.ac.uk"), person(given = c("Alexandre", "B."), family = "Simas", role = "ctb", comment = "earlier version by"), person(given = c("Andrea", "V."), family = "Rocha", role = "ctb", comment = "earlier version by"))
# Description: Beta regression for modeling beta-distributed dependent variables, e.g., rates and proportions. In addition to maximum likelihood regression (for both mean and precision of a beta-distributed response), bias-corrected and bias-reduced estimation as well as finite mixture models and recursive partitioning for beta regressions are provided.
# Depends: R (>= 3.0.0)
# Imports: graphics, grDevices, methods, stats, flexmix, Formula, lmtest, modeltools, sandwich
# Suggests: car, lattice, partykit, strucchange
# License: GPL-2 | GPL-3
# NeedsCompilation: no
# Packaged: 2019-05-16 09:55:07 UTC; zeileis
# Author: Achim Zeileis [aut, cre], Francisco Cribari-Neto [aut], Bettina Gruen [aut], Ioannis Kosmidis [aut], Alexandre B. Simas [ctb] (earlier version by), Andrea V. Rocha [ctb] (earlier version by)
# Maintainer: Achim Zeileis <Achim.Zeileis@R-project.org>
# Repository: CRAN
# Date/Publication: 2019-05-16 19:52:50 UTC
