travis:
  secure:
    BINSTAR_TOKEN: qiYegWfOUJ4MOXCKY9ovDaN3Q1NSraSc84w/oUeV1GH1pY5tWPNAWBctuJ8hgZaRpqe3/5E9omvffo8LTnI/e4mpiLLnrZJ6yuB7vlDyKarPmbWqtTKm3Xuqg0r41exhn7IvKCfhj6UCb+d+qNqyAnwWhmhihZ2Oq3NdPxpNuI23EastU6Eb3wIYFe4aueTwhkl+nAs3ZErr0f0/Ru18SjMeJBgzrieCNAtY5m5kezzYpwj8nDAISeZ8BV01GQkRPU+hpv9DVqTh/lrTACoya50OeY1et5Mh0vFRpKAXF8mUWdTOXoR5SSh7SPtTS3NOGwxGDhcWDo+gCkBUbpUjoKY7c1p4uzJDvvRlmw4CBXXxbvP/R5rQw728J5ylQoFKV9/HujahKJgf1KOo0vLCtVZHpMnoiLqnWXBWMcdw+Je4TwfCoeGq5VR4cMyf/gXyVNgDi187cjCGQfgRQ14m7YRtl34V+n5qFai9cJhMCAj/aDAkHF6q6ICy8yjaYQgSNVuokU22FO/lw7Yz6Er8f2Gjd6088TWqfaQC7DRoHAfm+H4uIxMDGzAAN+KgixY2GDeBh4Phn2p3Ld88J1wmb+iF5iEXSo2v0PdYYKAjls8KCt22iZ+5YsJYoaZWr5GkictDCH6FwEgH2MWZNrrLRNGNKgkj+cOGQIBZkFIkiEc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
