travis:
  secure:
    BINSTAR_TOKEN: YiRSUsbtey3ApazkZBkcBRR9Ff8rTyctAg4sZhHc4KBjffMkx8w39zSH5+EJTEa2Xjjer92i4sTg324wGoB33C/H80VriGlDkwS7TF8xmRVz8RIpbqwCbA6u3a+iL2zgecJEezh1mXX9AESQRK00PnjDymfcZngwoNW/HH/0J7eagx1qamqHr0mQVVylv1eMBm7yvCsdKk5kn6ZnByo7xbJfNDH3c0azQXJCJz5YznaCRnbrwkV6fViKsmzJYIxwP85oz/yvcE2Q0GFtN6Na+yWdq64kv+YHKTngTlwCFhKVTZ1z6KA2E2FQnSygU0Kk59GBo44NaBqSINoyJ46ZU0nM88UFeJVGLoIv/dc+NgM9QaEzhxU7tiQxCjMNzjW0OfJ9oLKRTUaKbYYWKwXS+Aj7zAQgjbo1Wkb8mOjUkHr6ddIS4v8JBJsJ8hl9UjpTw5ouf3McpOgj99iaPHGiEH6FelAZwAtwKFFVW9o/8KK+Moqmch5FqwO9vVLdadUOZ47ipy8xSaXYnMFC47S/5yQiidr8N0oFtyefO/mwKn5JXburjZJF2aRjYYgibm3eZXHG8vUcfTY+/flkLZfiZVN40JzTx1LNlWgDYdkxt58gUMT4odZOWHbUQur7dBOqQ6E/FIE6H/qGfv+1MWHjOyGtCy5rdwYlZmD+jKzegHs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
